//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lhub_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_lhub
    {
        public string Article_ID { get; set; }
        public string Article_text { get; set; }
        public string Article_video { get; set; }
        public string Article_Record { get; set; }
    }
}
