//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lhub_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_lhub
    {
        public string USER_id { get; set; }
        public string USER_name { get; set; }
        public string USER_Email { get; set; }
        public string USER_password { get; set; }
    }
}
